# Generated by Django 5.1.3 on 2025-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_equipo_mensajecontacto_noticia_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
