# Generated by Django 5.1.7 on 2025-04-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
