# Generated by Django 5.1.7 on 2025-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_alter_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
